/// Flutter icons SentroIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SentroIcon
///      fonts:
///       - asset: fonts/SentroIcon.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class SentroIcon {
  SentroIcon._();

  static const _kFontFam = 'SentroIcon';
  static const String? _kFontPkg = null;

  static const IconData academic_writing =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_down =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_left =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_right =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action_up =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData activate =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_image_fill =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_image =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_cart_2_fill =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_cart_2 =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_cart_fill =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_cart =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adjustment_fill =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adjustment =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adult_fill =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adult =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData announcement_fill =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData announcement =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award_bronze_fill =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award_bronze =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award_silver_fill =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award_silver =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award_trophy_fill =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award_trophy =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blog_fill =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blog =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boat_fill =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boat =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_fill =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bot_fill =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bot =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_empty_fill =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_fill =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_no_data_fill =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_no_data =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_somethings_fill =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_somethings =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData build_fill =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building_fill =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData build =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_analyst_fill =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_analyst =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_fill =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_fill =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_fill =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_fill =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_fill =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData charge_normal_fill =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData charge_normal =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData charge_super_fill =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData charge_super =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_fill =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle_fill =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_frame_fill =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_frame =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_square_fill =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_square =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData child_fill =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clean_fill =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData child =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clean =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_circle_fill =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_circle =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_frame_fill =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_frame =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_cirle_frame_fill =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_square_fill =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_cirle_frame =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_square_frame_fill =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_square =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_square_frame =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color_palete_fill =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comedy_fill =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comedy =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color_palete =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_fill =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compare =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compare_fill =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_fill =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_cut =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_minus_circle_fill =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_minus_circle =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_minus_cirle_frame_fill =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_minus_cirle_frame =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_minus_frame_fill =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_minus_frame =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_minus_square_fill =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_minus_square_frame_fill =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_minus_square_frame =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_minus_square =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_minus =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_plus_circle_fill =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_plus_circle =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_plus_cirle_frame_fill =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_plus_cirle_frame =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_plus_copy =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_plus_frame_fill =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_plus_frame =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_plus_square_fill =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_plus_square_frame_fill =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_plus_square_frame =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_plus_square =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_plus =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy_fill =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData darkmode =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deactivate =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData decrease_chart_fill =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData decrease_chart =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_fill =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData designer_fill =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData designer =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData development_fill =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData development =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike_fill =
      IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_fill =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_fill =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drag_2_fill =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drag_2 =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drag =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_fill =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit =
      IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emoji_fill =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emoji =
      IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eraser_fill =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eraser =
      IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error =
      IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand =
      IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData external_icon =
      IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face_id =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq_2_fill =
      IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq_2 =
      IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq_fill =
      IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq =
      IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_fill =
      IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite =
      IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female =
      IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData field_date =
      IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData field_number =
      IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData field_selection =
      IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData field_text =
      IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_fill =
      IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint_straight =
      IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint_tilt =
      IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_fill =
      IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag =
      IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flight_from_fill =
      IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flight_from =
      IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flight_to_fill =
      IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flight_to =
      IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_empty_fill =
      IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_empty =
      IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_error_fill =
      IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_error =
      IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_fill =
      IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_somethings_fill =
      IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_somethings =
      IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder =
      IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_contains_fill =
      IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_contains =
      IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData full_screen_fill =
      IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData full_screen =
      IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_fill =
      IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift =
      IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grammar_fill =
      IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grammar =
      IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_view_fill =
      IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_view =
      IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_fill =
      IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group =
      IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData growth_chart_ =
      IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData growth_chart_fill =
      IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_fill =
      IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide_copy =
      IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide =
      IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history =
      IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_fill =
      IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idea_fill =
      IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idea =
      IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_360 =
      IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_fill =
      IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image =
      IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox_fill =
      IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox =
      IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information_fill =
      IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information =
      IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData interview_fill =
      IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData interview =
      IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language_fill =
      IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language =
      IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_fill =
      IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop =
      IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layer_fill =
      IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layer =
      IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_fill =
      IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like =
      IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_broken =
      IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
      IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_view_fill =
      IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_view =
      IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loading =
      IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locaion_fill =
      IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_fill =
      IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login_fill =
      IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login =
      IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lyrics_fill =
      IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lyrics =
      IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magic_fill =
      IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magic =
      IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData make_up_fill =
      IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData make_up =
      IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male =
      IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData melody =
      IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile_phone_fill =
      IconData(0xe8f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile_phone =
      IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horizontal =
      IconData(0xe8f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vertical =
      IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multiple_image_fill =
      IconData(0xe8f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_fill =
      IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music =
      IconData(0xe8fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute_fill =
      IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute =
      IconData(0xe8fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_left =
      IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_middle =
      IconData(0xe8ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_right =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData networking_fill =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData networking =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_chat_fill =
      IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_chat =
      IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newborn_fill =
      IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newborn =
      IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_on_fill =
      IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_on =
      IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passport_fill =
      IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passport =
      IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_fill =
      IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause =
      IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData peekaboo_hide =
      IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData peekaboo_show =
      IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pet_fill =
      IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pet =
      IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone =
      IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_fill =
      IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin =
      IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane_fill =
      IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane =
      IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_fill =
      IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play =
      IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poem_fill =
      IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poem =
      IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pos_fill =
      IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pos =
      IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pregnancy_fill =
      IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pregnancy =
      IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print =
      IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData professor_fill =
      IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData professor =
      IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_fill =
      IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile =
      IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code =
      IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_fill =
      IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question =
      IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record_audio_fill =
      IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record_audio =
      IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record_video_fill =
      IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record_video =
      IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh =
      IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply_fill =
      IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply =
      IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reset =
      IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_left_2 =
      IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_left =
      IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_right_2 =
      IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_right =
      IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_fill =
      IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save =
      IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_fill =
      IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_no_result_fill =
      IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_no_result =
      IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_fill =
      IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send =
      IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_fill =
      IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings =
      IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_fill =
      IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share =
      IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shipping_motocycle_2_fill =
      IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shipping_motocycle_2 =
      IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shipping_motocycle_fill =
      IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shipping_motocycle =
      IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag_fill =
      IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag =
      IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket_fill =
      IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket =
      IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart_fill =
      IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart =
      IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show_copy =
      IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show =
      IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_out_fill =
      IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_out =
      IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alphabet_down =
      IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alphabet_up =
      IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_down =
      IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_latest_down =
      IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_latest_up =
      IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_price_down =
      IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_price_up =
      IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_rating_down =
      IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_rating_up =
      IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_up =
      IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort =
      IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_fill =
      IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store_2_fill =
      IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store_2 =
      IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store_fill =
      IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store =
      IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storytelling_fill =
      IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storytelling =
      IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData student_fill =
      IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData student =
      IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscription_fill =
      IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscription =
      IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swipe_fill =
      IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swipe =
      IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet_fill =
      IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet =
      IconData(0xe966, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_fill =
      IconData(0xe967, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task_done =
      IconData(0xe969, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task_list =
      IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_align_center =
      IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_align_justify_left =
      IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_align_justify_right =
      IconData(0xe96d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_align_justify =
      IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_align_left =
      IconData(0xe96f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_align_right =
      IconData(0xe970, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_at =
      IconData(0xe971, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_bold =
      IconData(0xe972, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_code =
      IconData(0xe973, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_column_insert_left =
      IconData(0xe974, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_column_insert_right =
      IconData(0xe975, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_column_remove_left =
      IconData(0xe976, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_column_remove_right =
      IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_h1 =
      IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_h2 =
      IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_h3 =
      IconData(0xe97a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_italic =
      IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_list_bullet =
      IconData(0xe97c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_list_numberic =
      IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_paragraph =
      IconData(0xe97e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_quote =
      IconData(0xe97f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_row_insert_bottom =
      IconData(0xe980, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_row_insert_top =
      IconData(0xe981, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_row_remove_bottom =
      IconData(0xe982, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_row_remove_top =
      IconData(0xe983, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_strike =
      IconData(0xe984, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_table_insert =
      IconData(0xe985, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_table_remove =
      IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_text_highlight_2 =
      IconData(0xe987, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_text_highlight =
      IconData(0xe988, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData te_underline =
      IconData(0xe989, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_area =
      IconData(0xe98a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_scanner =
      IconData(0xe98b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_fill =
      IconData(0xe98c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket =
      IconData(0xe98d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_fill =
      IconData(0xe98e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time =
      IconData(0xe98f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toddler_fill =
      IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toddler =
      IconData(0xe991, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unbox_fill =
      IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unbox =
      IconData(0xe993, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock_fill =
      IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock =
      IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_fill =
      IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload =
      IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_banned_fill =
      IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_banned =
      IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_connect_fill =
      IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_connect =
      IconData(0xe99b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_settings_fill =
      IconData(0xe99c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_settings =
      IconData(0xe99d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vehicle_fill =
      IconData(0xe99e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vehicle =
      IconData(0xe99f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_fill =
      IconData(0xe9a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_not_fill =
      IconData(0xe9a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_not =
      IconData(0xe9a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified =
      IconData(0xe9a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_fill =
      IconData(0xe9a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_upload_fill =
      IconData(0xe9a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video =
      IconData(0xe9a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_contains_fill =
      IconData(0xe9a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_contains =
      IconData(0xe9a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_full_screen_fill =
      IconData(0xe9a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_full_screen =
      IconData(0xe9aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down_fill =
      IconData(0xe9ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down =
      IconData(0xe9ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_mute_fill =
      IconData(0xe9ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_mute =
      IconData(0xe9ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up_fill =
      IconData(0xe9af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up =
      IconData(0xe9b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_2_fill =
      IconData(0xe9b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_2 =
      IconData(0xe9b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_fill =
      IconData(0xe9b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet =
      IconData(0xe9b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning_fill =
      IconData(0xe9b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning =
      IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website_2_fill =
      IconData(0xe9b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website_2 =
      IconData(0xe9b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website_fill =
      IconData(0xe9b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website =
      IconData(0xe9ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whiteboard_fill =
      IconData(0xe9bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whiteboard =
      IconData(0xe9bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData worldwide_fill =
      IconData(0xe9bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData worldwide =
      IconData(0xe9be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in_fill =
      IconData(0xe9bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in =
      IconData(0xe9c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out_fill =
      IconData(0xe9c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out =
      IconData(0xe9c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const _kIconCodes = {
    'academic_writing': 0xe800,
    'action_down': 0xe801,
    'action_left': 0xe802,
    'action_right': 0xe803,
    'action_up': 0xe804,
    'activate': 0xe805,
    'add_image_fill': 0xe806,
    'add_image': 0xe807,
    'add_to_cart_2_fill': 0xe808,
    'add_to_cart_2': 0xe809,
    'add_to_cart_fill': 0xe80a,
    'add_to_cart': 0xe80b,
    'adjustment_fill': 0xe80c,
    'adjustment': 0xe80d,
    'adult_fill': 0xe80e,
    'adult': 0xe80f,
    'announcement_fill': 0xe810,
    'announcement': 0xe811,
    'arrow_down': 0xe812,
    'arrow_left': 0xe813,
    'arrow_right': 0xe814,
    'arrow_up': 0xe815,
    'attach': 0xe816,
    'award_bronze_fill': 0xe817,
    'award_bronze': 0xe818,
    'award_silver_fill': 0xe819,
    'award_silver': 0xe81a,
    'award_trophy_fill': 0xe81b,
    'award_trophy': 0xe81c,
    'blog_fill': 0xe81d,
    'blog': 0xe81e,
    'boat_fill': 0xe81f,
    'boat': 0xe820,
    'book_fill': 0xe821,
    'book': 0xe822,
    'bot_fill': 0xe823,
    'bot': 0xe824,
    'box_empty_fill': 0xe825,
    'box_fill': 0xe826,
    'box_no_data_fill': 0xe827,
    'box_no_data': 0xe828,
    'box_somethings_fill': 0xe829,
    'box_somethings': 0xe82a,
    'build_fill': 0xe82b,
    'building_fill': 0xe82c,
    'build': 0xe82d,
    'building': 0xe82e,
    'business_analyst_fill': 0xe82f,
    'business_analyst': 0xe830,
    'box': 0xe831,
    'business': 0xe832,
    'business_fill': 0xe833,
    'calendar_fill': 0xe834,
    'calendar': 0xe835,
    'camera_fill': 0xe836,
    'camera': 0xe837,
    'card_fill': 0xe838,
    'cash_fill': 0xe839,
    'card': 0xe83a,
    'cash': 0xe83b,
    'charge_normal_fill': 0xe83c,
    'charge_normal': 0xe83d,
    'charge_super_fill': 0xe83e,
    'charge_super': 0xe83f,
    'chat_fill': 0xe840,
    'chat': 0xe841,
    'check_circle_fill': 0xe842,
    'check_frame_fill': 0xe843,
    'check_frame': 0xe844,
    'check_square_fill': 0xe845,
    'check_circle': 0xe846,
    'check_square': 0xe847,
    'check': 0xe848,
    'chevron_down': 0xe849,
    'chevron_right': 0xe84a,
    'chevron_left': 0xe84b,
    'chevron_up': 0xe84c,
    'child_fill': 0xe84d,
    'clean_fill': 0xe84e,
    'child': 0xe84f,
    'clean': 0xe850,
    'clear_circle_fill': 0xe851,
    'clear_circle': 0xe852,
    'clear_frame_fill': 0xe853,
    'clear_frame': 0xe854,
    'clear_cirle_frame_fill': 0xe855,
    'clear_square_fill': 0xe856,
    'clear_cirle_frame': 0xe857,
    'clear_square_frame_fill': 0xe858,
    'clear_square': 0xe859,
    'clear_square_frame': 0xe85a,
    'color_palete_fill': 0xe85b,
    'comedy_fill': 0xe85c,
    'clear': 0xe85d,
    'comedy': 0xe85e,
    'color_palete': 0xe85f,
    'comment_fill': 0xe860,
    'compare': 0xe861,
    'compare_fill': 0xe862,
    'comment': 0xe863,
    'contact_fill': 0xe864,
    'contact': 0xe865,
    'control_cut': 0xe866,
    'control_minus_circle_fill': 0xe867,
    'control_minus_circle': 0xe868,
    'control_minus_cirle_frame_fill': 0xe869,
    'control_minus_cirle_frame': 0xe86a,
    'control_minus_frame_fill': 0xe86b,
    'control_minus_frame': 0xe86c,
    'control_minus_square_fill': 0xe86d,
    'control_minus_square_frame_fill': 0xe86e,
    'control_minus_square_frame': 0xe86f,
    'control_minus_square': 0xe870,
    'control_minus': 0xe871,
    'control_plus_circle_fill': 0xe872,
    'control_plus_circle': 0xe873,
    'control_plus_cirle_frame_fill': 0xe874,
    'control_plus_cirle_frame': 0xe875,
    'control_plus_copy': 0xe876,
    'control_plus_frame_fill': 0xe877,
    'control_plus_frame': 0xe878,
    'control_plus_square_fill': 0xe879,
    'control_plus_square_frame_fill': 0xe87a,
    'control_plus_square_frame': 0xe87b,
    'control_plus_square': 0xe87c,
    'control_plus': 0xe87d,
    'copy_fill': 0xe87e,
    'copy': 0xe87f,
    'darkmode': 0xe880,
    'deactivate': 0xe881,
    'decrease_chart_fill': 0xe882,
    'decrease_chart': 0xe883,
    'delete_fill': 0xe884,
    'delete': 0xe885,
    'designer_fill': 0xe886,
    'designer': 0xe887,
    'development_fill': 0xe888,
    'development': 0xe889,
    'dislike_fill': 0xe88a,
    'dislike': 0xe88b,
    'document_fill': 0xe88c,
    'document': 0xe88d,
    'download_fill': 0xe88e,
    'download': 0xe88f,
    'drag_2_fill': 0xe890,
    'drag_2': 0xe891,
    'drag': 0xe892,
    'edit_fill': 0xe893,
    'edit': 0xe894,
    'emoji_fill': 0xe895,
    'emoji': 0xe896,
    'eraser_fill': 0xe897,
    'eraser': 0xe898,
    'error': 0xe899,
    'expand': 0xe89a,
    'external_icon': 0xe89b,
    'face_id': 0xe89c,
    'faq_2_fill': 0xe89d,
    'faq_2': 0xe89e,
    'faq_fill': 0xe89f,
    'faq': 0xe8a0,
    'favorite_fill': 0xe8a1,
    'favorite': 0xe8a2,
    'female': 0xe8a3,
    'field_date': 0xe8a4,
    'field_number': 0xe8a5,
    'field_selection': 0xe8a6,
    'field_text': 0xe8a7,
    'filter_fill': 0xe8a8,
    'filter': 0xe8a9,
    'fingerprint_straight': 0xe8aa,
    'fingerprint_tilt': 0xe8ab,
    'flag_fill': 0xe8ac,
    'flag': 0xe8ad,
    'flight_from_fill': 0xe8ae,
    'flight_from': 0xe8af,
    'flight_to_fill': 0xe8b0,
    'flight_to': 0xe8b1,
    'folder_empty_fill': 0xe8b2,
    'folder_empty': 0xe8b3,
    'folder_error_fill': 0xe8b4,
    'folder_error': 0xe8b5,
    'folder_fill': 0xe8b6,
    'folder_somethings_fill': 0xe8b7,
    'folder_somethings': 0xe8b8,
    'folder': 0xe8b9,
    'frame_contains_fill': 0xe8ba,
    'frame_contains': 0xe8bb,
    'full_screen_fill': 0xe8bc,
    'full_screen': 0xe8bd,
    'gift_fill': 0xe8be,
    'gift': 0xe8bf,
    'grammar_fill': 0xe8c0,
    'grammar': 0xe8c1,
    'grid_view_fill': 0xe8c2,
    'grid_view': 0xe8c3,
    'group_fill': 0xe8c4,
    'group': 0xe8c5,
    'growth_chart_': 0xe8c6,
    'growth_chart_fill': 0xe8c7,
    'heart_fill': 0xe8c8,
    'heart': 0xe8c9,
    'hide_copy': 0xe8ca,
    'hide': 0xe8cb,
    'history': 0xe8cc,
    'home_fill': 0xe8cd,
    'home': 0xe8ce,
    'idea_fill': 0xe8cf,
    'idea': 0xe8d0,
    'image_360': 0xe8d1,
    'image_fill': 0xe8d2,
    'image': 0xe8d3,
    'inbox_fill': 0xe8d4,
    'inbox': 0xe8d5,
    'information_fill': 0xe8d6,
    'information': 0xe8d7,
    'interview_fill': 0xe8d8,
    'interview': 0xe8d9,
    'language_fill': 0xe8da,
    'language': 0xe8db,
    'laptop_fill': 0xe8dc,
    'laptop': 0xe8dd,
    'layer_fill': 0xe8de,
    'layer': 0xe8df,
    'like_fill': 0xe8e0,
    'like': 0xe8e1,
    'link_broken': 0xe8e2,
    'link': 0xe8e3,
    'list_view_fill': 0xe8e4,
    'list_view': 0xe8e5,
    'loading': 0xe8e6,
    'locaion_fill': 0xe8e7,
    'location': 0xe8e8,
    'lock_fill': 0xe8e9,
    'lock': 0xe8ea,
    'login_fill': 0xe8eb,
    'login': 0xe8ec,
    'lyrics_fill': 0xe8ed,
    'lyrics': 0xe8ee,
    'magic_fill': 0xe8ef,
    'magic': 0xe8f0,
    'make_up_fill': 0xe8f1,
    'make_up': 0xe8f2,
    'male': 0xe8f3,
    'melody': 0xe8f4,
    'mobile_phone_fill': 0xe8f5,
    'mobile_phone': 0xe8f6,
    'more_horizontal': 0xe8f7,
    'more_vertical': 0xe8f8,
    'multiple_image_fill': 0xe8f9,
    'music_fill': 0xe8fa,
    'music': 0xe8fb,
    'mute_fill': 0xe8fc,
    'mute': 0xe8fd,
    'nav_left': 0xe8fe,
    'nav_middle': 0xe8ff,
    'nav_right': 0xe900,
    'networking_fill': 0xe901,
    'networking': 0xe902,
    'new_chat_fill': 0xe903,
    'new_chat': 0xe904,
    'newborn_fill': 0xe905,
    'newborn': 0xe906,
    'notifications_on_fill': 0xe907,
    'notifications_on': 0xe908,
    'passport_fill': 0xe909,
    'passport': 0xe90a,
    'pause_fill': 0xe90b,
    'pause': 0xe90c,
    'peekaboo_hide': 0xe90d,
    'peekaboo_show': 0xe90e,
    'pet_fill': 0xe90f,
    'pet': 0xe910,
    'phone': 0xe911,
    'pin_fill': 0xe912,
    'pin': 0xe913,
    'plane_fill': 0xe914,
    'plane': 0xe915,
    'play_fill': 0xe916,
    'play': 0xe917,
    'poem_fill': 0xe918,
    'poem': 0xe919,
    'pos_fill': 0xe91a,
    'pos': 0xe91b,
    'pregnancy_fill': 0xe91c,
    'pregnancy': 0xe91d,
    'print': 0xe91e,
    'professor_fill': 0xe91f,
    'professor': 0xe920,
    'profile_fill': 0xe921,
    'profile': 0xe922,
    'qr_code': 0xe923,
    'question_fill': 0xe924,
    'question': 0xe925,
    'record_audio_fill': 0xe926,
    'record_audio': 0xe927,
    'record_video_fill': 0xe928,
    'record_video': 0xe929,
    'refresh': 0xe92a,
    'reply_fill': 0xe92b,
    'reply': 0xe92c,
    'reset': 0xe92d,
    'rotate_left_2': 0xe92e,
    'rotate_left': 0xe92f,
    'rotate_right_2': 0xe930,
    'rotate_right': 0xe931,
    'save_fill': 0xe932,
    'save': 0xe933,
    'search_fill': 0xe934,
    'search_no_result_fill': 0xe935,
    'search_no_result': 0xe936,
    'search': 0xe937,
    'send_fill': 0xe938,
    'send': 0xe939,
    'settings_fill': 0xe93a,
    'settings': 0xe93b,
    'share_fill': 0xe93c,
    'share': 0xe93d,
    'shipping_motocycle_2_fill': 0xe93e,
    'shipping_motocycle_2': 0xe93f,
    'shipping_motocycle_fill': 0xe940,
    'shipping_motocycle': 0xe941,
    'shopping_bag_fill': 0xe942,
    'shopping_bag': 0xe943,
    'shopping_basket_fill': 0xe944,
    'shopping_basket': 0xe945,
    'shopping_cart_fill': 0xe946,
    'shopping_cart': 0xe947,
    'show_copy': 0xe948,
    'show': 0xe949,
    'sign_out_fill': 0xe94a,
    'sign_out': 0xe94b,
    'sort_alphabet_down': 0xe94c,
    'sort_alphabet_up': 0xe94d,
    'sort_down': 0xe94e,
    'sort_latest_down': 0xe94f,
    'sort_latest_up': 0xe950,
    'sort_price_down': 0xe951,
    'sort_price_up': 0xe952,
    'sort_rating_down': 0xe953,
    'sort_rating_up': 0xe954,
    'sort_up': 0xe955,
    'sort': 0xe956,
    'star_fill': 0xe957,
    'star': 0xe958,
    'store_2_fill': 0xe959,
    'store_2': 0xe95a,
    'store_fill': 0xe95b,
    'store': 0xe95c,
    'storytelling_fill': 0xe95d,
    'storytelling': 0xe95e,
    'student_fill': 0xe95f,
    'student': 0xe960,
    'subscription_fill': 0xe961,
    'subscription': 0xe962,
    'swipe_fill': 0xe963,
    'swipe': 0xe964,
    'tablet_fill': 0xe965,
    'tablet': 0xe966,
    'tag_fill': 0xe967,
    'tag': 0xe968,
    'task_done': 0xe969,
    'task_list': 0xe96a,
    'te_align_center': 0xe96b,
    'te_align_justify_left': 0xe96c,
    'te_align_justify_right': 0xe96d,
    'te_align_justify': 0xe96e,
    'te_align_left': 0xe96f,
    'te_align_right': 0xe970,
    'te_at': 0xe971,
    'te_bold': 0xe972,
    'te_code': 0xe973,
    'te_column_insert_left': 0xe974,
    'te_column_insert_right': 0xe975,
    'te_column_remove_left': 0xe976,
    'te_column_remove_right': 0xe977,
    'te_h1': 0xe978,
    'te_h2': 0xe979,
    'te_h3': 0xe97a,
    'te_italic': 0xe97b,
    'te_list_bullet': 0xe97c,
    'te_list_numberic': 0xe97d,
    'te_paragraph': 0xe97e,
    'te_quote': 0xe97f,
    'te_row_insert_bottom': 0xe980,
    'te_row_insert_top': 0xe981,
    'te_row_remove_bottom': 0xe982,
    'te_row_remove_top': 0xe983,
    'te_strike': 0xe984,
    'te_table_insert': 0xe985,
    'te_table_remove': 0xe986,
    'te_text_highlight_2': 0xe987,
    'te_text_highlight': 0xe988,
    'te_underline': 0xe989,
    'text_area': 0xe98a,
    'text_scanner': 0xe98b,
    'ticket_fill': 0xe98c,
    'ticket': 0xe98d,
    'time_fill': 0xe98e,
    'time': 0xe98f,
    'toddler_fill': 0xe990,
    'toddler': 0xe991,
    'unbox_fill': 0xe992,
    'unbox': 0xe993,
    'unlock_fill': 0xe994,
    'unlock': 0xe995,
    'upload_fill': 0xe996,
    'upload': 0xe997,
    'user_banned_fill': 0xe998,
    'user_banned': 0xe999,
    'user_connect_fill': 0xe99a,
    'user_connect': 0xe99b,
    'user_settings_fill': 0xe99c,
    'user_settings': 0xe99d,
    'vehicle_fill': 0xe99e,
    'vehicle': 0xe99f,
    'verified_fill': 0xe9a0,
    'verified_not_fill': 0xe9a1,
    'verified_not': 0xe9a2,
    'verified': 0xe9a3,
    'video_fill': 0xe9a4,
    'video_upload_fill': 0xe9a5,
    'video': 0xe9a6,
    'view_contains_fill': 0xe9a7,
    'view_contains': 0xe9a8,
    'view_full_screen_fill': 0xe9a9,
    'view_full_screen': 0xe9aa,
    'volume_down_fill': 0xe9ab,
    'volume_down': 0xe9ac,
    'volume_mute_fill': 0xe9ad,
    'volume_mute': 0xe9ae,
    'volume_up_fill': 0xe9af,
    'volume_up': 0xe9b0,
    'wallet_2_fill': 0xe9b1,
    'wallet_2': 0xe9b2,
    'wallet_fill': 0xe9b3,
    'wallet': 0xe9b4,
    'warning_fill': 0xe9b5,
    'warning': 0xe9b6,
    'website_2_fill': 0xe9b7,
    'website_2': 0xe9b8,
    'website_fill': 0xe9b9,
    'website': 0xe9ba,
    'whiteboard_fill': 0xe9bb,
    'whiteboard': 0xe9bc,
    'worldwide_fill': 0xe9bd,
    'worldwide': 0xe9be,
    'zoom_in_fill': 0xe9bf,
    'zoom_in': 0xe9c0,
    'zoom_out_fill': 0xe9c1,
    'zoom_out': 0xe9c2,
  };

  static getIconByName(String name) => IconData(
        _kIconCodes[name] ?? _kIconCodes.entries.first.value,
        fontFamily: _kFontFam,
        fontPackage: _kFontPkg,
      );
}
